name = "prowlarr"
version = "1.0.0"
scope = "resource"
targets = ["vm"]

[dependencies]
requires = ["container-runtime"]
optional = ["flaresolverr"]

[runtime]
requirements = ["compose-service"]
services = ["prowlarr"]

[container]
container_type = "docker"
seed_indexers_torrent = ["LimeTorrents", "Nyaa.si", "showRSS", "The Pirate Bay", "YTS"]
seed_indexers_usenet = ["NZBFinder", "NZBGeek", "NinjaCentral", "DrunkenSlug", "Usenet Crawler", "altHUB", "SceneNZB"]

[image]
name = "lscr.io/linuxserver/prowlarr"
tag = "latest"

[ports]
published = ["9696:9696"]

[volumes]
mounts = ["${CONFIG_PATH}/prowlarr:/config"]

[ui]
enabled = true
port = 9696
path = "/"
name = "Prowlarr"
description = "Indexer manager"
